-- Phase 5 — add-on marketplace (upselling engine, PRD §5.2) + Stripe wiring
-- on invoices. Follows this org's proven Stripe pattern (see
-- growth/apps/codigo-internacional's stripeService.js): no Stripe SDK,
-- Payment Links created by hand in the Stripe dashboard (or pasted onto an
-- invoice by staff), the backend only verifies inbound webhook signatures.
CREATE TABLE IF NOT EXISTS addons_catalog (
  id             TEXT PRIMARY KEY,
  title          TEXT NOT NULL,
  description    TEXT,
  price          REAL NOT NULL,
  special_price  REAL,
  ai_banner_url  TEXT,          -- R2-hosted, pre-generated by an admin — not a live pipeline
  category       TEXT,
  is_active      INTEGER NOT NULL DEFAULT 1,
  created_by     TEXT,
  created_at     TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS project_addons (
  id           TEXT PRIMARY KEY,
  project_id   TEXT NOT NULL,
  addon_id     TEXT NOT NULL,
  status       TEXT NOT NULL DEFAULT 'PROPOSED', -- PROPOSED (by staff) | PURCHASED (by client)
  invoice_id   TEXT,           -- set when PURCHASED — the auto-generated invoice
  proposed_by  TEXT,
  created_at   TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at   TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Stripe fields on the existing invoices table, added here rather than in
-- migration 0005 since Stripe wiring is specifically a Phase 5 concern.
ALTER TABLE invoices ADD COLUMN stripe_payment_link TEXT;
ALTER TABLE invoices ADD COLUMN stripe_payment_intent TEXT;
